#!/bin/bash
# -*- mode: shell-script -*-
DIR=$(dirname $(realpath "$0"))
OPT="-d $DIR"

which stow >/dev/null 2>&1 || { echo "Unable to automatically install dotfiles: stow was not found"; exit 1; }

MODULES=$(cat $DIR/modules)

echo "Stowing modules:"
for module in $MODULES; do
    printf "  $module... "
    stow $OPT $module
    echo "done"
done

printf "Ensuring Spacemacs is initialized... "
cd "$DIR/"
git submodule init
git submodule update
printf "done\n"

printf "Configuring dunst theme...\n"
DUNST_CONFIG=~/.config/dunst
printf "\t"
$DUNST_CONFIG/xrdb_theme.sh
mv -f $DUNST_CONFIG/dunstrc_xr_colors $DUNST_CONFIG/dunstrc
printf "done\n"
