#!/bin/bash
# -*- mode: shell-script -*-

DIR="$HOME/.dotfiles"
OPT="-d $DIR"

MODULES="emacs i3 zsh"

echo "Stowing modules..."
for module in $MODULES; do
    stow $OPT $module
done

echo "DONE"

echo "Ensuring Spacemacs is initialized..."
cd "$DIR/"
git submodule init
git submodule update
echo "DONE"
