Why are dotfile repositories important? See https://dotfiles.github.io/.
* dotfiles
This repo currently has the following dotfiles:
- .zshrc
- .emacs.d
- .spacemacs.d
- .config/i3/config
- .config/i3status/config
- .Xresources
- .config/polybar/config
- .config/kitty/kitty.conf
** Requirements
The following are assumed to be installed:
- prezto (for a pleasant zsh experience)
- i3wm
- polybar
- rofi (required by i3)
- acpi (required by i3blocks for battery indicator)
- feh (required for background)
- Font Awesome (required by polybar)
- Roboto font (required by polybar)
- sysstat (required by i3blocks for cpu usage)
- pacman-contrib (required by i3blocks for update checking)
- pulseaudio
- ponymix (used for pulseaudio volume control)
- pywal (used for tty colorscheme restoration)
- [color-blend](https://www.github.com/towerism/color-blend) (used for calculating colors)
** Optional
The following are optional:
- GNU Stow (recommended if you want to run the auto-install script)
- compton (optional for cool animations and transparency)
- Franz (for cloud services)
- Spotify
- kitty (preferred terminal)
** Usage
You should edit ~install~ and change ~DIR~ to where you cloned the repository.
You may have to remove existing dotfiles if they are not already managed by GNU
stow. After cloning, running the install script will set up the symlinks for
you:
#+BEGIN_SRC
$ git clone https://github.com/towerism/dotfiles ~/.dotfiles
$ ~/.dotfiles/install
#+END_SRC

*** `.loginssh`
You can override the unlocking of your ssh key by creating a script at
`$HOME/.loginssh`. The zshrc will be invoked with once for each of your private
keys. The identities array in the zshrc will determine which keys are unlocked.
If `.loginssh` is not provided, zshrc will fallback to prezto ssh unlocking.
** .zshrc
It automatically starts the emacs daemon and gives several aliases to
~emacsclient -t~. It also provides good defaults, including fuzzy completion,
and git integration.
** .emacs.d
This is essentially a snapshot of Spacemacs. Updating this submodule will update the Spacemacs emacs distribution.

** .spacemacs.d
This is the configuration dotfile for Spacemacs. Any custom layers will go in here.
** i3config
This is a modified version of the default config. Window navigation was modified
to mirror vim bindings exactly, so horizontal splitting had to be remapped. I've
also configured certain programs to open to certain workspaces, i.e. emacs open
in the code workspaces, and chromium opens in the www workspace.
** polybar
This config shows a pretty status bar at the top of the screen. It shows
battery, storage capacity used, volume, memory and cpu usage, wifi, power menu,
and workspaces that are pinned to the corresponding monitor.
** i3lock
You can use i3lock-fancy instead which will blur your screen and give you a
password prompt. Creating a systemd unit in ~/usr/lib/systemd/system~ will allow
you to lock the screen before sleeping the system. See this [[https://bbs.archlinux.org/viewtopic.php?id=150058][thread]] for more
info. 

If issues are encountered with black screen upon wake, check to make sure
mkinitcpio hooks includes resume and kernel parameters sets resume=</dev/sdaX>,
where X is swap partition. If you still have problems, then it is likely a
graphics driver issue.
** .Xresources
This config sets up the Monokai theme for URxvt. It also hides the URxvt's scrollbar.
