* dotfiles
This repo currently has the following dotfiles:
- .zshrc
- .emacs.d
** Requirements
The following are assumed to be installed:
- [[https://github.com/skwp/dotfiles][yadr]] (required by .zshrc)
- Cask (required by .emacs.d)
** Usage
You may have to remove existing dotfiles if they are not already symlinks. After
cloning, running the install script will set up the symlinks for you:
#+BEGIN_SRC
$ git clone https://github.com/towerism/dotfiles ~/.dotfiles
$ ~/.dotfiles/install
#+END_SRC
** .zshrc
It automatically starts the emacs daemon and gives several aliases to
~emacsclient -t~. It also provides good defaults, including fuzzy completion,
and git integration.
** .emacs.d
The emacs configuration was inspired by [[http://www.github.com/syl20bnr/spacemacs][Spacemacs]], which was my first foray
into emacs. However, Spacemacs was too bloated for me. Thus, I am essentially
taking my most commonly used features from Spacemacs and putting them into my
own config without all the extra bloat.
