# Shell variables
# Generated by 'wal'
wallpaper='/home/mfracker/.wallpapers/colorscheme-skyline-sunset.png'

# Special
background='#131116'
foreground='#e4dfbe'
cursor='#e4dfbe'

# Colors
color0='#131116'
color1='#976D56'
color2='#D5963D'
color3='#F9AB3E'
color4='#EEA547'
color5='#FBC170'
color6='#38BAF5'
color7='#e4dfbe'
color8='#9f9c85'
color9='#976D56'
color10='#D5963D'
color11='#F9AB3E'
color12='#EEA547'
color13='#FBC170'
color14='#38BAF5'
color15='#e4dfbe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
