# Shell variables
# Generated by 'wal'
wallpaper='/home/mfracker/.wallpapers/spacemacs.png'

# Special
background='#0B1A2F'
foreground='#cacad1'
cursor='#cacad1'

# Colors
color0='#0B1A2F'
color1='#595B75'
color2='#585886'
color3='#6B6A96'
color4='#71719E'
color5='#7F80A5'
color6='#8E8EB0'
color7='#cacad1'
color8='#8d8d92'
color9='#595B75'
color10='#585886'
color11='#6B6A96'
color12='#71719E'
color13='#7F80A5'
color14='#8E8EB0'
color15='#cacad1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
