#!/bin/zsh

SELECTED_COMMAND=$(tac .zhistory | sed "s/^:[^;]*;//g" | fzf)

if [ ! -z "$SELECTED_COMMAND" ]; then
  print -s "$SELECTED_COMMAND" # add the command to zhistory
  eval "$SELECTED_COMMAND"
fi
