#!/usr/bin/osascript

on run wallpaper
    set windowCount to 8
    repeat with X from 1 to windowCount
        tell application "Finder"
            tell application "System Events"
                if X > 1 then
                    key code 124 using control down ## move right
                    delay 1
                end if
                set deskGroup to (a reference to every desktop)
                repeat with theDesk in deskGroup
                    set picture of theDesk to wallpaper
                end repeat
            end tell
            delay 1
        end tell
    end repeat
end run
