#!/bin/bash

WALLPAPER_DIR=~/.wallpapers

SELECTED_THEME=$(ls $WALLPAPER_DIR | rofi -dmenu -p "theme")

if [ "current theme" = "$SELECTED_THEME" ]; then
  echo "not changing theme"
  exit 0
elif [ ! -z $SELECTED_THEME ]; then
  echo "changing theme"
  ~/.scripts/load-theme $WALLPAPER_DIR/$SELECTED_THEME > /dev/null
  exit 0
fi
echo "theme not selected"
exit 1
